# -*- coding: utf-8 -*-
"""z PyTpePro(SupplementaryProject).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQ8aEXCCw68b0jt9qiQibJmd5pnlcBNN
"""

from time import time, sleep
import random as r
import os

def mistakes(partest, usertest):
    error = 0
    for i in range(len(partest)):
        try:
            if partest[i] != usertest[i]:
                error += 1
        except:
            error += 1
    return error

def speed_time(time_s, time_e, userinput):
    time_delay = time_e - time_s
    time_r = round(time_delay, 2)
    speed = len(userinput) / time_r
    return round(speed, 2)


print("                           ***** PYTYPE PRO *****")
print("Test your typing speed and accuracy.")
print("Rules:")
print("- Type the given sentence quickly and accurately.")
print("- Your typing speed and errors will be displayed.")
print("- Play as many rounds as you like.")
print("- Your average speed will be calculated.")
sleep(5)
os.system('cls')
while True:
    ck = input("Ready to test? (Yes/No): ").lower()
    if ck == "yes":
        os.system('cls')
        test_sentences = ["Python is a coding language",
                              "mitochondria is the powerhouse of the cell",
                              "tiger is the national animal of india",
                              "please keep quiet at the library",
                              "the quick brown fox jumps over the lazy dog"
                             ]
        test_sentence = r.choice(test_sentences)

        print(test_sentence.upper())
        print("\n" * 2)
        time_1 = time()
        test_input = input("Type here: ")
        time_2 = time()

        typing_speed = speed_time(time_1, time_2, test_input)
        error_count = mistakes(test_sentence, test_input)
        os.system('cls')
        print("\nResults:\n")
        print(f"         Speed: {typing_speed} characters/sec")
        print(f"         Errors: {error_count}")

        if typing_speed >= 20 and error_count == 0:
            print("Excellent! You typed accurately and quickly!")
        elif typing_speed >= 15 and error_count <= 2:
            print("Good job! You typed fairly quickly with few errors.")
        elif typing_speed >= 10:
            print("Keep practicing! You're improving.")
        else:
            print("Keep practicing! You can improve your speed.")

        sleep(3)
        os.system('cls')
    elif ck == "no":
        print("Thank you for using the typing speed calculator.")
        break
    else:
        print("Invalid input. Please enter 'Yes' or 'No'.")